# Generated by Django 2.2.3 on 2019-10-07 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('time_req', models.CharField(max_length=20)),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Author')),
            ],
        ),
    ]
